### ISSUE TITLE
tumblr plis

### ISSUE THREAD

**Issue by alexanderkurniawans** [ijash/hostredirectindonesia#2]
tolong dong gan unblock tumblr via host, pake proxy lemot soalnya :(

**Comment by alexanderkurniawans** [comment]
thxx :)

**Comment by sicheater** [comment]
ok nanti ane kabarin

2018-04-25 1:54 GMT+07:00 alexanderkurniawans <notifications@github.com>:

**Comment by Tanuki33** [comment]
nih gan tambahin aja di hosts

217.12.15.83    cookiex.ngd.yahoo.com
66.6.32.162    px.srvcs.tumblr.com
87.248.116.12    assets.tumblr.com
87.248.116.14    www.tumblr.com
66.6.32.28    safe.txmblr.com
108.177.127.113    play.google.com
23.206.81.225    itunes.apple.com
54.230.92.233    embed.tumblr.com
108.177.127.100    www.google-analytics.com
184.50.167.203    sb.scorecardresearch.com
87.248.116.11    platform.tumblr.com
66.6.32.21    older-men-lover.tumblr.com

**Comment by BossyBigBoss** [comment]
Yet another good theme related article about how to unblock websites in Indonesia at http://vpnprivacy.services/news/how-to-unblock-websites-in-indonesia/ It will give you a few interesting ideas.

**Comment by ijash** [comment]
> nih gan tambahin aja di hosts
> 
> 217.12.15.83 cookiex.ngd.yahoo.com
> 66.6.32.162 px.srvcs.tumblr.com
> 87.248.116.12 assets.tumblr.com
> 87.248.116.14 [www.tumblr.com](http://www.tumblr.com)
> 66.6.32.28 safe.txmblr.com
> 108.177.127.113 play.google.com
> 23.206.81.225 itunes.apple.com
> 54.230.92.233 embed.tumblr.com
> 108.177.127.100 [www.google-analytics.com](http://www.google-analytics.com)
> 184.50.167.203 sb.scorecardresearch.com
> 87.248.116.11 platform.tumblr.com
> 66.6.32.21 older-men-lover.tumblr.com

sori baru bales. udh di update sesuai yg itu..
nanti pull request langsung aja
